INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (0,1,4,0,0,2,0,3,5,0,6,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Vôleibol', 1);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (0, 1,5,0,0,2,3,0,0,4,0,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Canoagem Slalom', 2);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (1, 2,3,0,0,0,0,4,0,5,0,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Capoeira', 3);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (1, 3,5,0,0,2,0,0,0,4,0,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Ciclismo Bmx', 4);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (0, 0,2,0,0,0,1,0,0,3,0,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Ciclismo De Estrada', 5);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (3, 0,4,0,0,2,0,1,0,0,0,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Ciclismo De Pista', 6);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (3, 2,5,0,0,0,1,0,0,4,0,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Ciclismo Moutain Bike', 7);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (0, 1,3,0,0,0,0,2,0,0,0,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Canoagem', 8);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (0, 1,3,0,0,2,0,0,0,0,0,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Críquete ', 9);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (1, 2,4,0,0,0,0,3,5,6,0,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Esgrima - Florete', 10);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (0, 1,4,0,0,3,0,2,5,6,7,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Esgrima - Sabre', 11);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (2, 1,4,0,0,3,0,0,0,5,0,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Frescobol', 12);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (4, 1,0,0,0,5,2,3,0,6,0,7);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Futebol', 13);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (0, 0,0,4,2,1,0,3,5,0,0,6);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Futebol Americano', 14);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (3, 2,0,0,0,0,1,0,0,0,0,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Futebol De Areia', 15);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (3, 2,5,0,0,0,0,1,4,0,0,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Esgrima - Espada', 16);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (3, 2,0,0,0,1,0,4,0,0,5,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Boxe', 17);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (2, 1,3,0,0,0,0,0,0,0,0,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Biribol', 18);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (0, 2,4,0,0,1,0,3,0,5,0,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Beisebol/Softbol', 19);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (0, 3,5,2,0,0,0,1,4,0,0,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Atletismo - Corrida de Velocidade', 20);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (0, 3,0,0,0,0,1,2,0,0,0,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Atletismo - Corridas De Fundo', 21);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (0, 3,0,4,0,0,1,2,0,0,0,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Atletismo - Corridas De Meio-Fundo', 22);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (6, 1,8,5,9,2,4,3,7,10,0,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Atletismo - Decatlo', 23);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (6, 1,7,5,0,2,4,3,0,0,0,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Atletismo - Heptatlo', 24);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (0, 4,6,5,0,1,0,2,0,0,3,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Atletismo - Lançamento De Dardo', 25);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (0, 2,6,4,0,1,0,3,0,0,5,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Atletismo - Lançamento De Disco', 26);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (0, 3,0,2,0,1,0,4,5,0,0,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Atletismo - Lançamento De Martelo ', 27);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (0, 1,4,0,0,2,0,3,5,6,4,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Atletismo - Salto Com Vara', 28);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (3, 2,4,0,0,1,0,0,0,5,0,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Atletismo - Salto Em Altura', 29);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (0, 3,4,5,0,2,0,1,0,6,0,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Atletismo - Salto Em Distância', 30);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (0, 2,4,0,0,3,0,1,5,6,0,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Atletismo - Salto Triplo', 31);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (0, 1,0,0,0,0,2,0,0,0,0,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Automobilismo', 32);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (1, 0,5,0,3,2,0,0,4,0,0,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Badminton', 33);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (3, 2,7,0,0,4,0,1,5,8,6,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Basquetebol', 34);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (1, 2,0,0,0,4,0,3,0,0,0,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Futsal/Futebol De Salão', 35);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (1, 2,0,0,0,3,0,0,0,0,0,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Futvôlei', 36);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (2, 1,4,0,0,3,0,5,0,0,0,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Ginástica Artística ', 37);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (4, 2,5,6,0,1,0,3,0,0,0,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Ginástica De Trampolim', 38);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (0, 3,4,0,0,2,0,1,6,0,5,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Natação Velocidade', 39);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (4, 1,6,7,0,5,2,3,0,8,0,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Pentatlo Moderno', 40);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (6, 1,5,0,0,2,4,3,0,0,7,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Polo Aquático ', 41);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (0, 2,8,4,0,1,7,6,5,0,3,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Remo', 42);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (5, 6,8,0,2,1,0,3,4,0,0,7);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Rúgby', 43);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (2, 1,3,0,0,4,0,0,0,5,0,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Saltos Ornamentais ', 44);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (2, 1,3,0,0,0,0,4,0,0,5,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Skate ', 45);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (2, 1,3,0,0,0,4,5,0,6,0,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Surfe', 46);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (3, 2,4,0,0,1,0,5,0,0,6,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Taekowondo', 47);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (2, 1,3,0,0,5,0,0,6,0,4,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Tênis ', 48);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (0, 1,3,0,0,5,0,2,0,6,4,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Tênis De Mesa', 49);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (0, 1,4,0,0,0,0,0,0,5,2,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Tiro Com Arco', 50);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (0, 1,0,0,0,0,2,0,0,3,0,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Tiro Esportivo ', 51);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (3, 0,0,6,0,4,1,2,5,0,0,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Triatlo ', 52);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (0, 1,0,0,0,0,0,0,0,2,0,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Vela ', 53);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (0, 2,6,3,0,0,1,0,5,0,4,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Natação Meio Fundo', 54);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (0, 4,0,2,0,1,0,5,0,3,0,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Atletismo - Arremesso de Peso', 55);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (0, 2,3,0,0,0,1,0,5,0,4,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Natação Fundo', 56);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (0, 2,3,0,0,0,1,0,0,0,4,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Maratona Aquática ', 57);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (2, 1,4,0,0,3,0,5,0,0,0,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Ginástica Rítmica', 58);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (0, 1,0,0,0,2,3,0,0,0,4,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Golfe', 59);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (1, 2,6,0,0,3,0,4,5,0,0,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Handebol', 60);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (0, 1,0,0,0,0,2,0,0,3,0,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Hipismo Adestramento', 61);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (2, 1,0,0,0,0,3,0,0,4,0,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Hipismo Concurso Completo', 62);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (2, 1,0,0,0,0,3,0,0,4,0,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Hipismo Saltos', 63);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (1, 3,5,0,0,2,4,0,0,0,0,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Hóquei Sobre Grama', 64);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (2, 1,7,5,0,4,0,3,0,0,0,6);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Jiu-Jitsu', 65);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (2, 1,7,4,5,3,0,0,0,0,0,6);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Judô', 66);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (4, 2,7,0,6,1,0,3,0,8,5,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Karatê', 67);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (2, 1,5,0,0,4,0,3,0,0,0,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Kung Fu', 68);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (0, 0,4,1,3,2,0,0,6,5,0,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Levantamento De Pesos', 69);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (5, 4,7,0,2,1,3,0,0,6,0,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Luta Estilo Livre', 70);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (1, 0,5,0,3,2,4,0,0,6,0,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Luta Greco-Romana', 71);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (0, 0,4,0,0,0,1,2,0,0,3,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Maratona', 72);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (2, 1,3,0,0,0,0,0,0,0,0,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Nado Sincronizado ', 73);
INSERT INTO perfil_esportista_padrao(agilidade, coordenacao_motora, flexibilidade, forca, hipertrofia, potencia, resistencia, velocidade, envergadura_estatura, compr_pernas_estatura, altura_tronco_cefalica_estatura, imc) VALUES (3, 2,4,0,0,0,1,0,6,7,5,0);
INSERT INTO esporte(nome, id_perfil_esportista_padrao) VALUES ('Vôlei De Praia ', 74);
INSERT INTO graduacao(nome) VALUES ('Dança - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Educação Física - Licenciatura');
INSERT INTO graduacao(nome) VALUES ('Dança - Licenciatura');
INSERT INTO graduacao(nome) VALUES ('Design - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Direito - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Educação Física - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Enfermagem - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Engenharia Metalúrgica - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Engenharia Agrícola - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Engenharia Ambiental e Sanitária - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Engenharia Cartográfica e de Agrimensura - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Engenharia Civil - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Engenharia de Alimentos - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Engenharia de Bioprocessos - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Cinema e Audiovisual - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Engenharia Aeronáutica - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Ciências Sociais - Licenciatura');
INSERT INTO graduacao(nome) VALUES ('Arquitetura e Urbanismo - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Ciências Naturais - Licenciatura');
INSERT INTO graduacao(nome) VALUES ('Administração - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Agronomia - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Arqueologia - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Engenharia de Computação - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Arquivologia - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Artes Visuais - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Artes Visuais - Licenciatura');
INSERT INTO graduacao(nome) VALUES ('Biblioteconomia - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Biomedicina - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Ciência da Computação - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Ciências Biológicas - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Ciências Biológicas - Licenciatura');
INSERT INTO graduacao(nome) VALUES ('Ciências Atuariais - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Ciências Contábeis - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Ciências Econômicas - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Ciências Sociais - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Engenharia Mecânica de Veículos Militares - Bacharelado (oferta exclusiva das Forças Armadas)');
INSERT INTO graduacao(nome) VALUES ('Engenharia de Controle e Automação - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Engenharia de Materiais - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Medicina Veterinária - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Medicina - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Matemática - Licenciatura');
INSERT INTO graduacao(nome) VALUES ('Engenharia Mecânica de Armamentos - Bacharelado (oferta exclusiva das Forças Armadas)');
INSERT INTO graduacao(nome) VALUES ('Letras - Língua Portuguesa - Licenciatura');
INSERT INTO graduacao(nome) VALUES ('Letras - Língua Estrangeira - Licenciatura');
INSERT INTO graduacao(nome) VALUES ('Letras - Língua Portuguesa - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Letras - Língua Estrangeira - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Jornalismo - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Informática - Licenciatura');
INSERT INTO graduacao(nome) VALUES ('História - Licenciatura');
INSERT INTO graduacao(nome) VALUES ('História - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Geologia - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Geografia - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Geografia - Licenciatura');
INSERT INTO graduacao(nome) VALUES ('Fonoaudiologia - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Fisioterapia - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Física - Licenciatura');
INSERT INTO graduacao(nome) VALUES ('Física - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Filosofia - Licenciatura');
INSERT INTO graduacao(nome) VALUES ('Filosofia - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Farmácia - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Estatística - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Engenharia Têxtil - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Engenharia Química - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Engenharia Nuclear - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Engenharia Naval - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Meteorologia - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Museologia - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Música - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Música - Licenciatura');
INSERT INTO graduacao(nome) VALUES ('Engenharia de Minas - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Engenharia de Pesca - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Engenharia de Petróleo - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Engenharia de Produção - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Engenharia de Telecomunicações - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Engenharia Elétrica - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Engenharia Eletrônica - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Engenharia Florestal - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Engenharia Mecânica - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Zootecnia - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Turismo - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Terapia Ocupacional - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Teologia - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Engenharia de Fortificação e Construção - Bacharelado (oferta exclusiva das Forças Armadas)');
INSERT INTO graduacao(nome) VALUES ('Teatro - Licenciatura');
INSERT INTO graduacao(nome) VALUES ('Sistemas da Informação - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Serviço Social - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Secretariado Executivo - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Relações Públicas - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Relações Internacionais - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Radio, TV, Internet (Comunicação Audiovisual e Multimídia) - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Química - Licenciatura');
INSERT INTO graduacao(nome) VALUES ('Química - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Publicidade e Propaganda - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Psicologia - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Pedagogia - Licenciatura');
INSERT INTO graduacao(nome) VALUES ('Odontologia - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Nutrição - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Teatro - Bacharelado');
INSERT INTO graduacao(nome) VALUES ('Matemática - Bacharelado');
INSERT INTO custom_role(name) VALUES('ROLE_ADMIN'), ('ROLE_USER'), ('ROLE_INTERVIEWER'), ('ROLE_INTERVIEWEE');
INSERT INTO custom_user(username, password) VALUES('epigen@email.com', '$2a$10$tNMWVoWKxqsu7gG.yOzxAemX7Bj0eFm0PTWhmd1VTy9gfxQVN02VG');
INSERT INTO user_role(id_user, id_role) VALUES(1,1), (1,2);
